apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-scrapper
  labels:
    app: market-scrapper
spec:
  selector:
    matchLabels:
      app: market-scrapper
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: market-scrapper
    spec:
      containers:
      - name: market-scrapper-auchan
        image: mrbolas/market_crawler:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_HOST
          value: "redis-cart"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_DB
          value: "0"
        command: ["MarketScrapper"]
        args: ["-t","Auchan"]
      - name: market-scrapper-continente
        image: mrbolas/market_crawler:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_HOST
          value: "redis-cart"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_DB
          value: "0"
        command: ["MarketScrapper"]
        args: ["-t","Continente"]